services:
  fetureflag:
    image: elcioabrahao/featureflag:latest
    container_name: featureflag
    restart: always
    ports:
      - 8081:8081
    links:
      - redis
    networks:
      - net01
    depends_on:
      - redis
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - net01
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
    networks:
      - net01

volumes:
  redis_volume_data:
  redis_insight_volume_data:

networks:
  net01:
    name: net01
